### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by NaroaCS** [CityScope/VehicleClustering#20]
Hi @tmightyquinn  @jmugicagonz ! 
I have a quick question about the log files, what does the 'level' variable determine?  
We define logging levels here: 
https://github.com/CityScope/VehicleClustering/blob/d5fd379e97a3d7e890614b747dfca9c271dbf165/CS_CityScope_GAMA/models/Loggers.gaml#L50
And use them here
https://github.com/CityScope/VehicleClustering/blob/d5fd379e97a3d7e890614b747dfca9c271dbf165/CS_CityScope_GAMA/models/Loggers.gaml#L21

**Comment by tmightyquinn** [comment]
Hi Naroa! These are used to determine how many logs actually go through. Basically, each time we log something, we assign it an importance. The logging level then determines whether we want every log message ever, or only the most important ones.

This is useful in the specific case of pheromones. Logging every pheromone value for every intersection all the time us pretty time intensive, and only slightly important. Its useful to be able to quickly enable and disable those logs.

Also, Printing level does the exact same thing, except for printing to the console instead of saving to a log file.

**Comment by NaroaCS** [comment]
Great, that's very nice! Thanks for the quick response @tmightyquinn 👍
