### ISSUE TITLE
Questions about Pheromones

### ISSUE THREAD

**Issue by NaroaCS** [CityScope/VehicleClustering#4]
Hi @agrignard, @LAAP. (I don't have Edu's GitHub, it would be great if you could add him to this conversation)
 
Together with @tmightyquinn and @jmugicagonz, we had gathered these questions about the previous UrbanSwarn simulation, could you help us with this?

1. What does the pheromone_mark represent?
2. Why are exploratoryRate and diffusion related as they are? (diffusion = (1-exploratoryRate)/2)
3. What are pheromone_roads? What is the purpose of these pheromone values? Who uses them, and for what? How are they marked (sth like: max distance to point, etc.)
4. Should pheromone evaporation be proportional to time or the number of cycles?
5. How many times should an RFID tag be updated by a given bike?
6. Why do bikes move into the low_battery state when batteryLife < lastDistanceToChargingStation/speed? Why divide by speed?

**Comment by agrignard** [comment]
Dear @NaroaCS those are very relevant question, however I might not be the best one to answer to it. As I far as I remember and according to this publication https://ieeexplore.ieee.org/abstract/document/8794020 it would be great to see if @AntonLuca would be happy yo help us to answer to those question ?

@NaroaCS for your question, would it possible to be a bit more specific and point to the corresponding file.gaml and ideally the line you are referring to?

**Comment by NaroaCS** [comment]
Dear @agrignard and @Antonluca.

Thank you, that could be very helpful! I leave here the questions with the specific references to the code. 

1. What does the pheromone_mark represent?
https://github.com/mitmedialab/UrbanSwarms/blob/945a5a84728cb78aaa7dee9c7a4b7deb94de138f/UrbanSwarm/models/UrbanSwarm_main.gaml#L305
2. Why are exploratoryRate and diffusion related as they are? (diffusion = (1-exploratoryRate)/2)
https://github.com/mitmedialab/UrbanSwarms/blob/945a5a84728cb78aaa7dee9c7a4b7deb94de138f/UrbanSwarm/models/swarmBot.gaml#L16
3. What are pheromone_roads? What is the purpose of these pheromone values? Who uses them, and for what? How are they marked (sth like: max distance to point, etc.)
https://github.com/mitmedialab/UrbanSwarms/blob/945a5a84728cb78aaa7dee9c7a4b7deb94de138f/UrbanSwarm/models/UrbanSwarm_main.gaml#L208
4. Should pheromone evaporation be proportional to time or the number of cycles? + 5. How many times should an RFID tag be updated by a given bike?  In the original code, it is done once per cycle so if we change the cycle the tags will be updated with different frequencies. We changed the code and in ours, it is just updated once per road segment. Probably marking should happen once per segment but evaporation should be somehow proportional to time?
https://github.com/mitmedialab/UrbanSwarms/blob/945a5a84728cb78aaa7dee9c7a4b7deb94de138f/UrbanSwarm/models/swarmBot.gaml#L340
6. Why do bikes move into the low_battery state when batteryLife < lastDistanceToChargingStation/speed? Why divide by speed?
https://github.com/mitmedialab/UrbanSwarms/blob/945a5a84728cb78aaa7dee9c7a4b7deb94de138f/UrbanSwarm/models/swarmBot.gaml#L264

@tmightyquinn, @jmugicagonz take a look at this just in case I missed anything please

**Comment by alfeoAntonioLuca** [comment]
Hi, @AntonLuca here (using a new account)
1) The mark represents the presence of garbage currently being disposed of by the robot, it is used to mark the path toward the position where the garbage has been found and to guide the other robots to that.

2) from the point of view of the design of the solution the two concepts are closely linked and for this reason, their measures have been bound: the exploratoryRate is the probability that even in the presence of pheromone mark is chosen a random direction, the diffusion parameters the amount of pheromone to be released once taken this path. The greater the possibility of random exploration, the lower the diffusion rate must be, otherwise, the system would converge with great difficulty to a stable swarm behavior.

3) pheromone_roads are used for visualization purposes: they do not play a role in the algorithm but represent the amount of pheromones associated with each segment of the urban path.

4) The evaporation must necessarily be proportional to the time, and it is updated every time a robot passes on the RFID tag by considering the last update time instant. This allows not to have a centralized structure for the update of the pheromone mark, but to let the robots take care of these when they pass over RFID tags. It is also possible to think of a centralized system that constantly updates the amount of pheromone in all RFID tags.

5) The "Low battery" status means that there is only time left to return to the nearest depot before the battery is completely exhausted. Considering the temporal discretization of the model the number of ticks of life left is the division between the distance to the depot and the speed of the robot.

**Comment by agrignard** [comment]
Great @Antonluca (good to hear form you), thank you so much for taking time to answer. I hope this will help @NaroaCS and her team!

**Comment by NaroaCS** [comment]
Yes, fixed for now! Will open a new one if we have more questions in the future. Thanks very much @alfeoAntonioLuca @agrignard, it was very helpful
